### ISSUE TITLE
DEVIL datasets used for training

### ISSUE THREAD

**Issue by unclebuff** [MichiganCOG/devil#1]
Thanks for your work.
I'm interesting about video inpainting, but I found that popular datasets such as DAVIS and YT-VOS are not quite appropriate for the mission.  Since significant portion of them has too big annotations in the view to be inpainted, which is useless for the training process.
I wonder if you have ever consider use DEVIL datasets for training process and if you have done it, how it works?

**Comment by rszeto** [comment]
Thanks for your interest in the project! DEVIL was primarily designed with evaluation in mind, so we have not tried using the data for training. If you are interested in using smaller masks, feel free to play with the mask code [here](https://github.com/MichiganCOG/devil/tree/public/src/fvi_masks).
